version: '2'

services:
  firefox:
    image: redelivre/standalone-firefox-debug
    build:
      context: .
      dockerfile: Dockerfile.firefox
      args:
        - "username=$username"
        - "pwd=$pwd"

  whatsapp:
    image: redelivre/whatsapp
    build:
      context: .
      dockerfile: Dockerfile.whatsapp
      args:
        - "username=$username"
        - "pwd=$pwd"
