FROM redelivre/standalone-firefox-debug
ARG username
ARG cache
ARG botname
ARG client
ENV SELENIUM_CLIENT=$client
COPY . /home/$username/selenium
USER $username
WORKDIR /home/$username/selenium
EXPOSE 9200
RUN sudo chown -R $username: /home/$username/selenium \
    && ls -la
CMD  python lib/whatsapp.py --username=`cat /proc/sys/kernel/random/uuid`
