version: '2'

services:
  firefox:
    image: redelivre/standalone-firefox-debug
    build:
      context: .
      dockerfile: Dockerfile.firefox
      args:
        - "username=seluser"
        - "pwd=secret"

  whatsapp:
    image: redelivre/whatsapp
    build:
      context: .
      dockerfile: Dockerfile.whatsapp
      args:
        - "username=seluser"
        - "botname=mybot"
